[phases.setup]
nixPkgs = ["python311", "pip"]

[phases.install]
cmds = [
  "pip install -r requirements.txt",
  "playwright install-deps",
  "playwright install chromium"
]

[phases.build]
cmds = ["echo 'Build phase completed'"]

[start]
cmd = "python start.py"