# Zeabur 部署配置文件 - 纯API版本
# 专为 Zeabur 平台优化的配置
# 版本: v2.0 - 纯API方案，完全避免浏览器依赖问题

[build]
# 纯API版本 - 使用默认Dockerfile（已优化为纯API版本）
# 版本标识: API-v2.0-20250114
# Zeabur会自动检测并使用Dockerfile

# 强制重建配置
nocache = true

# 使用Zeabur专用Playwright版本 - 预装Playwright镜像（推荐）
buildCommand = "docker build -f Dockerfile.zeabur -t bytedance-job-monitor ."

# 备选方案（如需要）：
# buildCommand = "docker build -f Dockerfile.selenium -t bytedance-job-monitor ."  # Selenium版本
# buildCommand = "docker build -f Dockerfile -t bytedance-job-monitor ."          # 原版Playwright

# 简化版API（备选4）- 基础API方案
# buildCommand = "docker build -f Dockerfile.simple -t bytedance-jobs-monitor-simple ."

[deploy]
# Playwright版本启动命令
startCommand = "python -m gunicorn --bind 0.0.0.0:8080 --workers 1 --timeout 120 app:app"

# 备选启动命令：
# startCommand = "python app.py"          # 直接启动（开发用）
# startCommand = "python app_selenium.py"  # Selenium版本
# startCommand = "python app_api_only.py"  # 纯API版本

# 环境变量
[env]
FLASK_ENV = "production"
FLASK_DEBUG = "False"
PYTHONPATH = "/app"
DATA_DIR = "/app/data"

# 健康检查
[health]
path = "/"
port = "$PORT"

[resources]
# Playwright版本配置（推荐）- 浏览器功能完整
memory = "2GB"    # Playwright需要更多内存
cpu = "1.0"       # 一个完整核心

# 备选配置：
# memory = "1GB"   # Selenium版本（轻量级浏览器）

# 超时配置 - 防止构建和启动超时
[timeout]
build = 900       # 构建超时15分钟（Playwright镜像较大）
start = 180       # 启动超时3分钟
# cpu = "0.5"
# memory = "512MB" # 纯API版本（资源需求最低）
# cpu = "0.25"

[timeout]
# Playwright版本超时配置（需要更多时间安装浏览器）
build = 600     # 构建超时10分钟（包含浏览器安装）
start = 120     # 启动超时2分钟

# 持久化存储
[volumes]
"/app/data" = "data-volume"