# Zeabur 部署配置文件
# 专为 Zeabur 平台优化的配置
# 基于测试结果，推荐使用原版Playwright方案以避免反爬虫问题

[build]
# Zeabur专用构建（推荐）- 针对Zeabur平台优化的Playwright配置
buildCommand = "docker build -f Dockerfile.zeabur -t bytedance-job-monitor ."

# 原版构建（备选）- 标准Playwright配置
# buildCommand = "docker build -t bytedance-job-monitor ."

# 简化版构建（不推荐）- API方式存在反爬虫问题，数据获取成功率低
# buildCommand = "docker build -f Dockerfile.simple -t bytedance-jobs-monitor-simple ."

[deploy]
# 原版部署（推荐）- 稳定可靠的数据获取
startCommand = "gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 120 app:app"

# 简化版部署（不推荐）- 存在反爬虫限制
# startCommand = "python start_simple.py"

# 环境变量
[env]
FLASK_ENV = "production"
FLASK_DEBUG = "False"
PYTHONPATH = "/app"
DATA_DIR = "/app/data"

# 健康检查
[health]
path = "/"
port = "$PORT"

# 资源配置（针对Playwright优化）
[resources]
memory = "2GB"  # Playwright需要更多内存
cpu = "1.0"     # 提升CPU配置以支持浏览器渲染

# 超时配置
[timeout]
build = 600     # 构建超时10分钟（Playwright安装需要时间）
start = 120     # 启动超时2分钟

# 持久化存储
[volumes]
"/app/data" = "data-volume"