# Zeabur 部署配置文件 - 纯API版本
# 专为 Zeabur 平台优化的配置
# 版本: v2.0 - 纯API方案，完全避免浏览器依赖问题

[build]
# 纯API版本 - 使用默认Dockerfile（已优化为纯API版本）
# 版本标识: API-v2.0-20250114
# Zeabur会自动检测并使用Dockerfile

# 强制重建配置
nocache = true

# Zeabur专用Playwright版本（备选1）- 预装Playwright镜像
# buildCommand = "docker build -f Dockerfile.zeabur -t bytedance-job-monitor ."

# Selenium版本（备选2）- 轻量级浏览器方案
# buildCommand = "docker build -f Dockerfile.selenium -t bytedance-job-monitor ."

# 原版Playwright（备选3）- 标准配置
# buildCommand = "docker build -t bytedance-job-monitor ."

# 简化版API（备选4）- 基础API方案
# buildCommand = "docker build -f Dockerfile.simple -t bytedance-jobs-monitor-simple ."

[deploy]
# 纯API版本启动命令（推荐）
startCommand = "python app_api_only.py"

# 其他版本启动命令（备选）
# startCommand = "python app.py"          # 原版Playwright
# startCommand = "python app_selenium.py"  # Selenium版本
# startCommand = "python start_simple.py" # 简化版API

# 环境变量
[env]
FLASK_ENV = "production"
FLASK_DEBUG = "False"
PYTHONPATH = "/app"
DATA_DIR = "/app/data"

# 健康检查
[health]
path = "/"
port = "$PORT"

[resources]
# 纯API版本配置（推荐）- 资源需求最低
memory = "512MB"  # 纯API版本只需要512MB
cpu = "0.25"      # 四分之一核心即可

# Playwright版本配置（如需要浏览器功能）
# memory = "2GB"
# cpu = "1.0"

# Selenium版本配置（轻量级浏览器）
# memory = "1GB"
# cpu = "0.5"

[timeout]
# 纯API版本超时配置（构建和启动都很快）
build = 300     # 构建超时5分钟（无浏览器依赖）
start = 60      # 启动超时1分钟

# 持久化存储
[volumes]
"/app/data" = "data-volume"