# Zeabur 部署配置文件
# 专为 Zeabur 平台优化的配置
# 基于测试结果，推荐使用原版Playwright方案以避免反爬虫问题

[build]
# Zeabur专用构建（推荐）- 针对Zeabur平台优化的Playwright配置
buildCommand = "docker build -f Dockerfile.zeabur -t bytedance-job-monitor ."

# 原版构建（备选）- 标准Playwright配置
# buildCommand = "docker build -t bytedance-job-monitor ."

# 简化版构建（不推荐）- API方式存在反爬虫问题，数据获取成功率低
# buildCommand = "docker build -f Dockerfile.simple -t bytedance-jobs-monitor-simple ."

[deploy]
# 原版部署（推荐）- 稳定可靠的数据获取
startCommand = "gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 120 app:app"

# 简化版部署（不推荐）- 存在反爬虫限制
# startCommand = "python start_simple.py"

# 环境变量
[env]
FLASK_ENV = "production"
FLASK_DEBUG = "False"
PYTHONPATH = "/app"
DATA_DIR = "/app/data"

# 健康检查
[health]
path = "/"
port = "$PORT"

[resources]
# 使用预装Playwright镜像的优化配置
memory = "2GB"  # 预装镜像需要更少内存
cpu = "1.0"     # 单核即可满足需求

# 原版方案配置（如果预装镜像不可用）
# memory = "4GB"
# cpu = "2.0"

# 简化版方案配置（不推荐，仅供参考）
# memory = "1GB"
# cpu = "0.5"

[timeout]
# 优化的超时配置（预装镜像构建更快）
build = 600     # 构建超时10分钟
start = 120     # 启动超时2分钟

# 持久化存储
[volumes]
"/app/data" = "data-volume"